### ISSUE TITLE
Add Spielplatzkarte to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [SupaplexOSM/spielplatzkarte#1]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add Spielplatzkarte to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by SupaplexOSM** [comment]
Thanks, just [added](https://github.com/taginfo/taginfo-projects/pull/196) the project to the TagInfo Projects list.
